=== ManojReddyPothuganti/Practice.April2017/StudentXMLSchema/src/main/resources/xsd/Student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Student" xmlns:tns="http://www.example.org/Student" elementFormDefault="qualified">

    <complexType name="Student">
    	<sequence>
    		<element name="Name" type="string"></element>
    		<element name="Address" type="tns:Address" maxOccurs="unbounded" minOccurs="1"></element>
    		<element name="Marks" type="tns:Marks" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="Address">
    	<sequence>
    		<element name="addressType">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="HOME"></enumeration>
    					<enumeration value="WORK"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="streetNo" type="string"></element>
    		<element name="city" type="string"></element>
    		<element name="state" type="string"></element>
    		<element name="zipcode" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="Marks">
    	<sequence>
    		<element name="subject" type="string"></element>
    		<element name="marks" type="double"></element>
    		<element name="maxMarks" type="double"></element>
    	</sequence>
    </complexType>

    <element name="Student" type="tns:Student"></element>

    <element name="Address" type="tns:Address"></element>

    <element name="Marks" type="tns:Marks"></element>
</schema>

=== ManojReddyPothuganti/Practice.April2017/StudentXMLSchema/src/main/resources/Student.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Student xmlns:tns="http://www.example.org/Student" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Student Student.xsd ">
  <tns:Name>Manoj</tns:Name>
  <tns:Address>
    <tns:addressType>HOME</tns:addressType>
    <tns:streetNo>5336</tns:streetNo>
    <tns:city>Kansas</tns:city>
    <tns:state>Missouri</tns:state>
    <tns:zipcode>66213</tns:zipcode>
  </tns:Address>
  <tns:Marks>
    <tns:subject>Maths</tns:subject>
    <tns:marks>75</tns:marks>
    <tns:maxMarks>80</tns:maxMarks>
  </tns:Marks>
</tns:Student>
